### ISSUE TITLE
toStringWithDecimalPlaces throws RangeError on zero

### ISSUE THREAD

**Issue by Bazinga9000** [Naruyoko/ExpantaNum.js#22]
Reproduction Steps:
`ExpantaNum.ZERO.toStringWithDecimalPlaces(3,true)`
raises the following error:
```
Uncaught RangeError: toFixed() digits argument must be between 0 and 100
    at Number.toFixed (<anonymous>)
    at decimalPlaces (eval at <anonymous> (test.js:102:12), <anonymous>:1213:31)
    at P.toStringWithDecimalPlaces (eval at <anonymous> (test.js:102:12), <anonymous>:1250:28)
    at <anonymous>:1:17
```
This works in the console on https://naruyoko.github.io/ExpantaNum.js/test.html, and also still errors when replacing `3` with any other integer.

**Comment by James103** [comment]
Can reproduce the error when running `new ExpantaNum(x).toStringWithDecimalPlaces(y,true)`, where x is any value that, after division by 10<sup>y</sup>, results in a number less than or equal to 10<sup>-100</sup>.

In particular, `new ExpantaNum(1e-97).toStringWithDecimalPlaces(3,true)` raises the same error, and so does `new ExpantaNum(1e-96).toStringWithDecimalPlaces(4,true)`.

**Comment by Naruyoko** [comment]
[α 1.4.0](https://github.com/Naruyoko/ExpantaNum.js/releases/tag/%CE%B1-1.4.0)
